from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QVBoxLayout, QHBoxLayout, QMessageBox)

question = QLabel('В каком году основана алгоритмика?')
btn_answer1 = QRadioButton('2013')
btn_answer2 = QRadioButton('2010')
btn_answer3 = QRadioButton('2016')
btn_answer4 = QRadioButton('2019')
layout_main = QVBoxLayout()
layoutH1 = QHBoxLayout()
layoutH2 = QHBoxLayout()
layoutH3 = QHBoxLayout()
layout.addWidget(question, alignment = Qt.AlignCenter)
layout.addWidget(btn_answer1, alignment = Qt.AlignCenter)
layout.addWidget(btn_answer2, alignment = Qt.AlignCenter)
layout.addWidget(btn_answer3, alignment = Qt.AlignCenter)
layout.addWidget(btn_answer4, alignment = Qt.AlignCenter)
layout_main - QVBoxLayout()
layout_main.addLayout(layoutH1)
layout_main.addLayout(layoutH2)
layout_main.addLayout(layoutH3)
main_win.setLayout(layout_main)

main_win.show()
app.exec_()